apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
spec:
  resources:
    - name: node-web-app-source
      type: git
    - name: node-web-app-image
      type: image
  tasks:
    - name: build
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1.11.0'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: node-web-app-source
        outputs:
          - name: image
            resource: node-web-app-image
      taskRef:
        kind: ClusterTask
        name: buildah
    - name: update-deployment
      params:
        - name: ARGS
          value: 
           - "patch"
           - "deployment/node-web-project"
           - "-p"
           - "'{\"spec\”:{\“replicas\”:0}}’"
      runAfter: build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: argocd-deploy
      params:
        - name: application-name
          value: 'node-web-app'
        - name: flags
          value: "--insecure"
        - name: argocd-version
          value: v1.4.2
      runAfter: update-deployment
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
