apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline
    spec:
      pipelineRef:
        name: node-web-app-pipeline
      resources:
      - name: node-web-app-source
        resourceRef:
          name: node-web-app-source
      - name: node-web-app-image
        resourceRef:
          name: node-web-app-image
      serviceAccountName: pipeline

--- 

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)

---

apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: node-web-app-tb
    template:
      name: node-web-app-tt