apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node-web-app-source
  namespace: argocd
spec:
  params:
    - name: url
      value: 'https://github.com/RolandOrg/node_web_app.git'
    - name: revision
      value: master
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node-web-app-image
  namespace: argocd
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/argocd/web_node_app'
  type: image
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: argocd
spec:
  params:
    - default: defaultValue
      name: PARAM_NAME
      type: string
  resources:
    - name: app-source
      type: git
    - name: app-image
      type: image
  tasks:
    - name: build
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1.11.0'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: node-web-app-source
        outputs:
          - name: image
            resource: node-web-app-image
      taskRef:
        kind: ClusterTask
        name: buildah
    - name: restart-deployment
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
