apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: node-web-app
  replicas: 4
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: image-registry.openshift-image-registry.svc:5000/argocd/web_node_app
        ports:
        - containerPort: 8080
